fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    group:
        group_class: App\Entity\UserGroup
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "no-reply@gamersx.tv"
        sender_name: "app@gamersx.tv"
