oneup_flysystem:
    adapters:
        gamersx_s3:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'

    filesystems:
        gamersx_s3:
            adapter: gamersx_s3
            alias: League\Flysystem\Filesystem
            mount: managed_files