sonata_admin:
    title: 'GamersX Admin'
    title_logo: '/images/controller.png'
    dashboard:
        groups:
            app.admin.group.home:
                label: Home Page
                items:
                    - admin.home_row
                    - admin.home_row_item
            sonata_user: ~

    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
