twig:
    globals:
        current_domain: '%env(CURRENT_DOMAIN)%'
        redirect_url: '%env(REDIRECT_URL)%'
        theme_setting: '@App\Repository\MasterSettingRepository'
        master_theme: '@App\Repository\MasterThemeRepository'
        site_settings: '@App\Repository\SiteSettingRepository'
        aws_s3_custom_uri_prefix: '%app.aws_s3_custom.uri_prefix%'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    file_name_pattern: '*.twig'

    form_themes:
        - 'form/custom_types.html.twig'

    paths:
        '%kernel.project_dir%/public/images': images

when@test:
    twig:
        strict_variables: true
