vich_uploader:
    db_driver: orm

    mappings:
       theme_banner:
           uri_prefix: /images/themes/
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       theme_embed:
           uri_prefix: /images/themes/
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       theme_art:
           uri_prefix: /images/themes/
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
