vich_uploader:
    db_driver: orm

    mappings:
       themes:
           uri_prefix: /images/themes/
           upload_destination: '%kernel.project_dir%/public/images/themes'
           directory_namer:
               namer: vich_uploader.namer_directory_property
               options: { property: 'twitchId' }
