vich_uploader:
    db_driver: orm

    mappings:
       theme_banner:
           uri_prefix: /images/themes
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'bannerImageSlug' }
       theme_embed:
           uri_prefix: /images/themes
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'embedBackgroundSlug' }
       theme_art:
           uri_prefix: /images/themes
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'customArtSlug' }
       theme_art_background:
           uri_prefix: /images/themes
           upload_destination: '%kernel.project_dir%/public/images/themes'
           namer:
               service: Vich\UploaderBundle\Naming\PropertyNamer
               options: { property: 'artBackgroundSlug' }
