version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/gamersx/codedeploy

hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: gamersx

permissions:
  - object: /var/www/gamersx/codedeploy
    owner: gamersx
    group: gamersx
