version: "3.5"
services:
  app:
    build:
      args:
        user: gamersx
        uid: 1000
      context: ./docker-compose/symfony/
      dockerfile: Dockerfile
    image: symfony
    container_name: gamersx-php
    volumes:
      - ./:/var/www
    networks:
      - gamersx
    restart: unless-stopped

  vue:
    image: node:lts-alpine
    container_name: gamersx-js
    user: '1000'
    working_dir: /var/www
    command: ['yarn', 'watch']
    volumes:
      - ./:/var/www
    networks:
      - gamersx
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: gamersx-web
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - gamersx
    restart: unless-stopped

networks:
  gamersx:
    driver: bridge
