# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.theme_path: '%kernel.project_dir%/public/images/themes/'
    app.images: '%kernel.project_dir%/public/images/'
    app.theme_url: '/images/themes/'
    app.twitch_secret: '%env(resolve:TWITCH_CLIENT_SECRET)%'
    app.twitch_id: '%env(resolve:TWITCH_CLIENT_ID)%'
    uploads_dir_name: 'uploads'
    uploads_base_url: '%env(SITE_BASE_URL)%/%uploads_dir_name%'
    timezone: '%env(APP_TIMEZONE)%'
    app.twitch_redirect_uri: '%env(resolve:TWITCH_REDIRECT_URI)%'
    app.aws_s3_bucket_name: '%env(AWS_S3_BUCKET_NAME)%'
    app.aws_s3_custom.uri_prefix: 'https://%env(AWS_S3_BUCKET_NAME)%.%env(AWS_S3_DOMAIN)%'
    app.aws_access_key_id: '%env(AWS_ACCESS_KEY_ID)%'
    app.aws_secret_access_key: '%env(resolve:AWS_SECRET_ACCESS_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

#    Sonata\AdminBundle\Templating\TemplateRegistry: '@sonata.admin.global_template_registry'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Containerizer/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Containerizer\ContainerizerFactory:
        arguments:
            - '@App\Service\TwitchApi'
            - '@App\Service\YouTubeApi'
            - '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            - '@logger'

    App\Command\CacheHomePageContainers:
        arguments:
            $redis_host: '%env(REDIS_HOST)%)'

    App\Controller\HomeController:
        arguments:
            $redis_host: '%env(REDIS_HOST)%)'

    admin.home_row:
        class: App\Admin\HomeRowAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\HomeRow, manager_type: orm, label: Rows }

    admin.home_row_item:
        class: App\Admin\HomeRowItemAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\HomeRowItem, manager_type: orm, label: Containers }

    admin.theme:
        class: App\Admin\ThemeAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Theme, manager_type: orm, label: Pages }

    admin.site_settings:
        class: App\Admin\SiteSettingsAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\SiteSettings, manager_type: orm, label: Site Settings }

    admin.partner:
        class: App\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Partner, manager_type: orm, label: Partners }

    admin.partner_role:
        class: App\Admin\PartnerRoleAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PartnerRole, manager_type: orm, label: Partner Roles }

    admin.container_access_control:
        class: App\Admin\ContainerAccessControlAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\HomeRowItemOperation, controller: App\Controller\ContainerAccessControlController, manager_type: orm, label: Container access control }

    Aws\S3\S3Client:
        arguments:
            -
                version: '%env(resolve:AWS_S3_VERSION)%' # or 'latest'
                region: '%env(resolve:AWS_REGION)%' # 'eu-central-1' for example
                credentials:
                    key: '%env(resolve:AWS_ACCESS_KEY_ID)%'
                    secret: '%env(resolve:AWS_SECRET_ACCESS_KEY)%'
